language: objective-c
osx_image: xcode8.3
xcode_project: ocPlayground.xcodeproj
xcode_schem: ocPlayground
script: xcodebuild -project ocPlayground.xcodeproj -scheme ocPlayground -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3' test
